os:
  linux
language: java
jdk:
  oraclejdk8
script:
#  ./mvnw clean package -DskipTests
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIJFF5CIWAOFFYPMQ
  secret_access_key:
    secure: 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
  region: eu-west-1
  app: cars-aws-demo
  env: dev
  bucket_name: cars-aws-demo-backet
  on:
    repo: cars-aws-demo/repo
    branch: dev