os:
  linux
language: java
jdk:
  oraclejdk8
script:
  ./mvnw clean package
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIJFF5CIWAOFFYPMQ
  secret_access_key:
    secure: 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
  region: eu-west-1
  app: cars-aws-demo
  env: dev
  bucket_name: elasticbeanstalk-eu-west-1-680513014599
  on:
    repo: https://github.com/jbogacz/cars-aws-demo.git
    branch: master